# Generated by Django 4.2.7 on 2025-11-13 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XXEScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=500)),
                ('endpoint', models.CharField(default='/data', max_length=200)),
                ('method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET')], default='POST', max_length=10)),
                ('file_to_read', models.CharField(default='/etc/passwd', max_length=500)),
                ('custom_headers', models.TextField(default='{"Content-Type": "application/xml"}', help_text='JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_used', models.TextField()),
                ('status_code', models.IntegerField()),
                ('response_body', models.TextField()),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tools.xxescan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
