# Generated by Django 4.2.7 on 2025-11-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xxescan',
            name='timeout',
            field=models.IntegerField(default=10),
        ),
    ]
