# Generated by Django 4.2.7 on 2025-11-13 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tools', '0002_xxescan_timeout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanresult',
            options={},
        ),
        migrations.AddField(
            model_name='xxescan',
            name='header_choice',
            field=models.CharField(choices=[('default', 'Default Headers'), ('custom', 'Custom Headers')], default='default', max_length=10),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='Tools.xxescan'),
        ),
        migrations.AlterField(
            model_name='xxescan',
            name='custom_headers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xxescan',
            name='method',
            field=models.CharField(default='POST', max_length=10),
        ),
        migrations.AlterField(
            model_name='xxescan',
            name='target_url',
            field=models.URLField(),
        ),
    ]
